name: pibic-2024-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas
  - matplotlib=3.8.2
  - seaborn
  - scikit-learn
  - pillow
  - jupyter
  - ipykernel
  - pip:
    - tensorflow==2.15.0
    - keras==2.15.0
    - tensorboard==2.15.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorflow-estimator==2.15.0
    - tensorflow-probability==0.23.0
    - ml-dtypes==0.2.0
    - opencv-python==4.8.1.78
    - albumentations==1.3.1
    - pytz==2023.3
    - python-dateutil==2.8.2
    - kiwisolver==1.4.5
    - cycler==0.12.1
    - fonttools==4.47.0
    - qudida==0.0.4
    - scikit-image==0.21.0 